window.phet = {}
window.phet.chipper = {}
window.phet.chipper.project = 'wave-on-a-string'
window.phet.chipper.version = '1.1.37'
window.phet.chipper.buildTimestamp = '2025-01-29 06:24:04 UTC'
window.phet.chipper.brand = 'phet'
window.phet.chipper.locale = 'es_MX'
window.phet.chipper.localeData = {
  es_MX: {
    englishName: 'Spanish, Mexico',
    localizedName: 'español (México)',
    direction: 'ltr',
    fallbackLocales: ['es'],
  },
}
window.phet.chipper.thirdPartyLicenseEntries = {
  lib: {
    'almond-0.2.9.js': {
      text: [
        'Copyright (c) 2011-2014, The Dojo Foundation All Rights Reserved.',
      ],
      projectURL: 'https://github.com/jrburke/almond',
      license: 'The MIT License',
      notes:
        'Allows a RequireJS-based simulation to run in its compiled (smaller, faster) form',
      licenseText: [
        'MIT License',
        '-----------',
        '',
        'Copyright (c) 2010-2011, The Dojo Foundation',
        '',
        'Permission is hereby granted, free of charge, to any person obtaining a copy',
        'of this software and associated documentation files (the "Software"), to deal',
        'in the Software without restriction, including without limitation the rights',
        'to use, copy, modify, merge, publish, distribute, sublicense, and/or sell',
        'copies of the Software, and to permit persons to whom the Software is',
        'furnished to do so, subject to the following conditions:',
        '',
        'The above copyright notice and this permission notice shall be included in',
        'all copies or substantial portions of the Software.',
        '',
        'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR',
        'IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,',
        'FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE',
        'AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER',
        'LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,',
        'OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN',
        'THE SOFTWARE.',
      ],
    },
    'FileSaver-b8054a2.js': {
      text: ['Copyright (c) 2015 Eli Grey. (http://eligrey.com)'],
      license: 'The MIT License',
      projectURL: 'https://github.com/eligrey/FileSaver.js',
      notes: 'Used for saving screenshot images',
      licenseText: [
        'Copyright © 2014 Eli Grey.',
        '',
        'Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:',
        '',
        'The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.',
        '',
        'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.',
        '',
      ],
    },
    'fontawesome-webfont-3.0.2.svg': {
      text: ['by Dave Gandy'],
      license: 'SIL Open Font License, Version 1.1',
      projectURL: 'https://github.com/FortAwesome/Font-Awesome/tree/v3.0.2',
      notes:
        'Provides shapes like the home icon and check box icons, used in FontAwesomeNode',
      licenseText: [
        'Copyright (c) 2013, Dave Gandy - http://fontawesome.io',
        'with Reserved Font Name Font Awesome.',
        '',
        'This Font Software is licensed under the SIL Open Font License, Version 1.1.',
        'This license is copied below, and is also available with a FAQ at:',
        'http://scripts.sil.org/OFL',
        '',
        '',
        '-----------------------------------------------------------',
        'SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007',
        '-----------------------------------------------------------',
        '',
        'PREAMBLE',
        'The goals of the Open Font License (OFL) are to stimulate worldwide',
        'development of collaborative font projects, to support the font creation',
        'efforts of academic and linguistic communities, and to provide a free and',
        'open framework in which fonts may be shared and improved in partnership',
        'with others.',
        '',
        'The OFL allows the licensed fonts to be used, studied, modified and',
        'redistributed freely as long as they are not sold by themselves. The',
        'fonts, including any derivative works, can be bundled, embedded,',
        'redistributed and/or sold with any software provided that any reserved',
        'names are not used by derivative works. The fonts and derivatives,',
        'however, cannot be released under any other type of license. The',
        'requirement for fonts to remain under this license does not apply',
        'to any document created using the fonts or their derivatives.',
        '',
        'DEFINITIONS',
        '"Font Software" refers to the set of files released by the Copyright',
        'Holder(s) under this license and clearly marked as such. This may',
        'include source files, build scripts and documentation.',
        '',
        '"Reserved Font Name" refers to any names specified as such after the',
        'copyright statement(s).',
        '',
        '"Original Version" refers to the collection of Font Software components as',
        'distributed by the Copyright Holder(s).',
        '',
        '"Modified Version" refers to any derivative made by adding to, deleting,',
        'or substituting -- in part or in whole -- any of the components of the',
        'Original Version, by changing formats or by porting the Font Software to a',
        'new environment.',
        '',
        '"Author" refers to any designer, engineer, programmer, technical',
        'writer or other person who contributed to the Font Software.',
        '',
        'PERMISSION & CONDITIONS',
        'Permission is hereby granted, free of charge, to any person obtaining',
        'a copy of the Font Software, to use, study, copy, merge, embed, modify,',
        'redistribute, and sell modified and unmodified copies of the Font',
        'Software, subject to the following conditions:',
        '',
        '1) Neither the Font Software nor any of its individual components,',
        'in Original or Modified Versions, may be sold by itself.',
        '',
        '2) Original or Modified Versions of the Font Software may be bundled,',
        'redistributed and/or sold with any software, provided that each copy',
        'contains the above copyright notice and this license. These can be',
        'included either as stand-alone text files, human-readable headers or',
        'in the appropriate machine-readable metadata fields within text or',
        'binary files as long as those fields can be easily viewed by the user.',
        '',
        '3) No Modified Version of the Font Software may use the Reserved Font',
        'Name(s) unless explicit written permission is granted by the corresponding',
        'Copyright Holder. This restriction only applies to the primary font name as',
        'presented to the users.',
        '',
        '4) The name(s) of the Copyright Holder(s) or the Author(s) of the Font',
        'Software shall not be used to promote, endorse or advertise any',
        'Modified Version, except to acknowledge the contribution(s) of the',
        'Copyright Holder(s) and the Author(s) or with their explicit written',
        'permission.',
        '',
        '5) The Font Software, modified or unmodified, in part or in whole,',
        'must be distributed entirely under this license, and must not be',
        'distributed under any other license. The requirement for fonts to',
        'remain under this license does not apply to any document created',
        'using the Font Software.',
        '',
        'TERMINATION',
        'This license becomes null and void if any of the above conditions are',
        'not met.',
        '',
        'DISCLAIMER',
        'THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,',
        'EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF',
        'MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT',
        'OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL THE',
        'COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,',
        'INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL',
        'DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING',
        'FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM',
        'OTHER DEALINGS IN THE FONT SOFTWARE.',
        '',
      ],
    },
    'game-up-camera-1.0.0.js': {
      text: ['Copyright (c) BrainPOP'],
      license: 'MIT',
      projectURL:
        'https://github.com/phetsims/sherpa/blob/master/lib/game-up-camera-1.0.0.js',
      notes:
        'Allows a simulation to return a snapshot to BrainPOP/GameUp/SnapThought',
      licenseText: [
        'The MIT License (MIT) Copyright (c) 2016 BrainPOP',
        '',
        'Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:',
        '',
        'The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.',
        '',
        'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.',
      ],
    },
    'jama-1.0.2': {
      text: ['a basic linear algebra package for Java.'],
      license: 'Public Domain',
      projectURL: 'http://math.nist.gov/javanumerics/jama/',
      notes:
        'A derived work (certain ported and modified files) is used in Dot, mainly for matrix decompositions. Used in assorted simulations.',
      licenseText: [
        'Public Domain',
        '',
        'Copyright Notice This software is a cooperative product of The MathWorks and the National Institute of Standards and Technology (NIST) which has been released to the public domain. ',
        'Neither The MathWorks nor NIST assumes any responsibility whatsoever for its use by other parties, and makes no guarantees, expressed or implied, about its quality, reliability, or any other characteristic.',
      ],
    },
    'jquery-2.1.0.js': {
      text: [
        'Copyright (c) 2005, 2014 jQuery Foundation, Inc. and other contributors',
        '(includes Sizzle.js, http://sizzlejs.com)',
      ],
      license: 'The MIT License',
      projectURL: 'http://jquery.com',
      notes:
        'Facilitates interaction with browser DOM elements, mainly used in Scenery',
      licenseText: [
        'Copyright 2013 jQuery Foundation and other contributors',
        'http://jquery.com/',
        '',
        'Permission is hereby granted, free of charge, to any person obtaining',
        'a copy of this software and associated documentation files (the',
        '"Software"), to deal in the Software without restriction, including',
        'without limitation the rights to use, copy, modify, merge, publish,',
        'distribute, sublicense, and/or sell copies of the Software, and to',
        'permit persons to whom the Software is furnished to do so, subject to',
        'the following conditions:',
        '',
        'The above copyright notice and this permission notice shall be',
        'included in all copies or substantial portions of the Software.',
        '',
        'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,',
        'EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF',
        'MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND',
        'NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE',
        'LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION',
        'OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION',
        'WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.',
      ],
    },
    'lodash-2.4.1.js': {
      text: [
        'Copyright (c) 2012-2013 The Dojo Foundation, http://dojofoundation.org>',
        'Based on Underscore.js 1.5.2, http://underscorejs.org/LICENSE',
        'Copyright (c) 2009-2013 Jeremy Ashkenas, DocumentCloud and Investigative Reporters & Editors',
      ],
      license: 'The MIT License',
      projectURL: 'http://lodash.com',
      notes:
        'Adds common data structure operations such as sorting, grouping, etc.',
      licenseText: [
        'Copyright 2012-2013 The Dojo Foundation <http://dojofoundation.org/>',
        'Based on Underscore.js 1.5.2, copyright 2009-2013 Jeremy Ashkenas,',
        'DocumentCloud and Investigative Reporters & Editors <http://underscorejs.org/>',
        '',
        'Permission is hereby granted, free of charge, to any person obtaining',
        'a copy of this software and associated documentation files (the',
        '"Software"), to deal in the Software without restriction, including',
        'without limitation the rights to use, copy, modify, merge, publish,',
        'distribute, sublicense, and/or sell copies of the Software, and to',
        'permit persons to whom the Software is furnished to do so, subject to',
        'the following conditions:',
        '',
        'The above copyright notice and this permission notice shall be',
        'included in all copies or substantial portions of the Software.',
        '',
        'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,',
        'EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF',
        'MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND',
        'NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE',
        'LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION',
        'OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION',
        'WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.',
      ],
    },
    'pegjs-0.7.0.js': {
      text: ['Copyright (c) 2010-2012 David Majda'],
      license: 'The MIT License',
      projectURL: 'http://pegjs.majda.cz',
      notes: 'Parser Generator for JavaScript. SVG path parsing in Kite',
      licenseText: [
        'Copyright (c) 2010-2012 David Majda',
        '',
        'Permission is hereby granted, free of charge, to any person',
        'obtaining a copy of this software and associated documentation',
        'files (the "Software"), to deal in the Software without',
        'restriction, including without limitation the rights to use,',
        'copy, modify, merge, publish, distribute, sublicense, and/or sell',
        'copies of the Software, and to permit persons to whom the',
        'Software is furnished to do so, subject to the following',
        'conditions:',
        '',
        'The above copyright notice and this permission notice shall be',
        'included in all copies or substantial portions of the Software.',
        '',
        'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,',
        'EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES',
        'OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND',
        'NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT',
        'HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,',
        'WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING',
        'FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR',
        'OTHER DEALINGS IN THE SOFTWARE.',
      ],
    },
    'seedrandom-2.4.2.js': {
      text: ['Copyright 2015 David Bau.'],
      license: 'MIT',
      projectURL: 'https://github.com/davidbau/seedrandom',
      notes: 'seeded random number generator for Javascript',
      licenseText: [
        'Copyright 2015 David Bau.',
        '',
        'Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated',
        'documentation files (the "Software"), to deal in the Software without restriction, including without limitation the',
        'rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit',
        'persons to whom the Software is furnished to do so, subject to the following conditions:',
        '',
        'The above copyright notice and this permission notice shall be included in all copies or substantial portions of the',
        'Software.',
        '',
        'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE',
        'WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR',
        'COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR',
        'OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.',
      ],
    },
    'text-2.0.12.js': {
      text: [
        'Copyright (c) 2010-2014, The Dojo Foundation All Rights Reserved.',
      ],
      license: 'The MIT License',
      projectURL: 'http://github.com/requirejs/text',
      notes:
        'Loads strings to be displayed in the sim, including internationalized strings.',
      licenseText: [
        'MIT License',
        '-----------',
        '',
        'Copyright (c) 2010-2011, The Dojo Foundation',
        '',
        'Permission is hereby granted, free of charge, to any person obtaining a copy',
        'of this software and associated documentation files (the "Software"), to deal',
        'in the Software without restriction, including without limitation the rights',
        'to use, copy, modify, merge, publish, distribute, sublicense, and/or sell',
        'copies of the Software, and to permit persons to whom the Software is',
        'furnished to do so, subject to the following conditions:',
        '',
        'The above copyright notice and this permission notice shall be included in',
        'all copies or substantial portions of the Software.',
        '',
        'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR',
        'IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,',
        'FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE',
        'AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER',
        'LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,',
        'OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN',
        'THE SOFTWARE.',
      ],
    },
  },
}
window.phet.chipper.dependencies = {
  comment:
    '# wave-on-a-string 1.1.37 Tue Jan 28 2025 23:24:01 GMT-0700 (Mountain Standard Time)',
  assert: {
    sha: '7d27130a4d27da15aa7f8a21bbfb9245288c1b44',
    branch: 'HEAD',
  },
  axon: {
    sha: '9457f36aec22935c7b5f41a9d0777255dd5d9884',
    branch: 'HEAD',
  },
  babel: {
    sha: 'd6680ac29b402638ffb1ddd9faedfbaa0dd287cb',
    branch: 'main',
  },
  brand: {
    sha: '78d99a4f0fefd28d3ccd1f221974a2735539f3fc',
    branch: 'HEAD',
  },
  chipper: {
    sha: 'eaf9f6dbd8d76ab912864f9bfe7e63872ab0b8e2',
    branch: 'HEAD',
  },
  dot: {
    sha: 'da78031b6f080d20bc8346beaa1d37148188371e',
    branch: 'HEAD',
  },
  joist: {
    sha: '6d373909a5241b67c0a12a8220d1546df2e2f078',
    branch: 'HEAD',
  },
  kite: {
    sha: '10ca8bf2b2712307ff528352de8451c0c8afe093',
    branch: 'HEAD',
  },
  'phet-core': {
    sha: 'de29611a6ac322da53a4302ca65f40ff9713e497',
    branch: 'HEAD',
  },
  phetcommon: {
    sha: 'cf3e0a6f5fce12a0a6876737686a99e2f179d58e',
    branch: 'HEAD',
  },
  phetmarks: {
    sha: '3fdfece0fe0262594bb06856833b8b16be25deb8',
    branch: 'HEAD',
  },
  scenery: {
    sha: 'cf2f7e7c1f08f40f9fc5933770c8a3832d377ecf',
    branch: 'HEAD',
  },
  'scenery-phet': {
    sha: '5bfc7b434914e859b004d3dd94eeec1e69ec1a8a',
    branch: 'HEAD',
  },
  sherpa: {
    sha: 'b999987ecbc9d23c011e8114f41ea486397c9f1c',
    branch: 'HEAD',
  },
  sun: {
    sha: '2b83e994039b2d33845d5e51d7735d144c188d97',
    branch: 'HEAD',
  },
  tandem: {
    sha: '2441eec6b422cb20e08682da02ab2bf7bf73250c',
    branch: 'HEAD',
  },
  'wave-on-a-string': {
    sha: 'd26962ca7f688f29d6ba2b1d9546bfc78118f6a9',
    branch: 'HEAD',
  },
}
window.phet.chipper.strings = {
  es_MX: {
    'JOIST/HomeButton.name': '‪Home‬',
    'JOIST/adaptedFrom': '‪adaptado\r\nde‬',
    'JOIST/termsPrivacyAndLicensing': '‪Términos, Privacidad y Licencias‬',
    'JOIST/translation.credits.link': '‪Créditos de traducción‬',
    'JOIST/thirdParty.credits.link': '‪Créditos a terceros‬',
    'JOIST/credits.title': '‪Créditos‬',
    'JOIST/credits.leadDesign': '‪Líder de Diseño: {0}‬',
    'JOIST/credits.softwareDevelopment': '‪Desarrollo de Software: {0}‬',
    'JOIST/credits.team': '‪Equipo: {0}‬',
    'JOIST/credits.qualityAssurance': '‪Seguro de calidad: {0}‬',
    'JOIST/credits.graphicArts': '‪Artes gráficas:{0}‬',
    'JOIST/credits.translation': '‪Traducción‬',
    'JOIST/credits.thanks': '‪Gracias‬',
    'JOIST/updates.upToDate': '‪Simulación actualizada‬',
    'JOIST/updates.outOfDate': '‪Nueva versión disponible‬',
    'JOIST/updates.checking': '‪Revisando Actualizaciones‬',
    'JOIST/updates.offline': '‪No se puede comprobar si hay actualizaciones.‬',
    'JOIST/updates.newVersionAvailable': '‪Nueva versión disponible: {0}‬',
    'JOIST/updates.yourCurrentVersion': '‪Versión actual: {0}‬',
    'JOIST/updates.getUpdate': '‪Obtener actualización‬',
    'JOIST/updates.noThanks': '‪No gracias‬',
    'JOIST/versionPattern': '‪versión {0}‬',
    'JOIST/options.title': '‪Opciones‬',
    'JOIST/showPointers': '‪Mostrar indicadores‬',
    'JOIST/done': '‪Hecho‬',
    'JOIST/title.settings': '‪Ajustes‬',
    'JOIST/menuItem.options': '‪Opciones...‬',
    'JOIST/menuItem.about': '‪Acerca de...‬',
    'JOIST/menuItem.mailInputEventsLog':
      '‪Registro de eventos de entrada de correo‬',
    'JOIST/menuItem.outputInputEventsLog':
      '‪Registro de eventos de entrada de salida‬',
    'JOIST/menuItem.phetWebsite': '‪Sitio web de PhET ...‬',
    'JOIST/menuItem.reportAProblem': '‪Reportar un problema...‬',
    'JOIST/menuItem.screenshot': '‪Captura de pantalla‬',
    'JOIST/menuItem.fullscreen': '‪Pantalla completa‬',
    'JOIST/menuItem.settings': '‪Ajustes...‬',
    'JOIST/menuItem.getUpdate': '‪Revisar actualizaciones‬',
    'JOIST/menuItem.submitInputEventsLog':
      '‪Enviar registro de eventos de entrada‬',
    'JOIST/PhetButton.name': '‪PhET Menu Button‬',
    'JOIST/titlePattern': '‪{0} {1}‬',
    'SCENERY_PHET/ResetAllButton.name': '‪Reset All‬',
    'WAVE_ON_A_STRING/rulers': '‪Reglas‬',
    'WAVE_ON_A_STRING/timer': '‪Cronómetro‬',
    'WAVE_ON_A_STRING/referenceLine': '‪Líneas de referencia‬',
    'WAVE_ON_A_STRING/tension': '‪tensión‬',
    'WAVE_ON_A_STRING/damping': '‪amortiguación‬',
    'WAVE_ON_A_STRING/low': '‪baja‬',
    'WAVE_ON_A_STRING/high': '‪alta‬',
    'WAVE_ON_A_STRING/none': '‪ninguna‬',
    'WAVE_ON_A_STRING/lots': '‪mucha‬',
    'WAVE_ON_A_STRING/frequency': '‪frecuecia‬',
    'WAVE_ON_A_STRING/patternValueUnitHz': '‪{0} Hz‬',
    'WAVE_ON_A_STRING/pulseWidth': '‪ancho del pulso‬',
    'WAVE_ON_A_STRING/patternValueUnitS': '‪{0} s‬',
    'WAVE_ON_A_STRING/amplitude': '‪amplitud‬',
    'WAVE_ON_A_STRING/patternValueUnitCm': '‪{0} cm‬',
    'WAVE_ON_A_STRING/restart': '‪Reiniciar‬',
    'WAVE_ON_A_STRING/speedSlow': '‪Movimiento lento‬',
    'WAVE_ON_A_STRING/speedNormal': '‪Normal‬',
    'WAVE_ON_A_STRING/manual': '‪Manual‬',
    'WAVE_ON_A_STRING/oscillate': '‪Oscilar‬',
    'WAVE_ON_A_STRING/pulse': '‪Pulso‬',
    'WAVE_ON_A_STRING/fixedEnd': '‪Extremo fijo‬',
    'WAVE_ON_A_STRING/looseEnd': '‪Extremo libre‬',
    'WAVE_ON_A_STRING/noEnd': '‪Sin extremo‬',
    'WAVE_ON_A_STRING/unitCm': '‪cm‬',
    'WAVE_ON_A_STRING/wave-on-a-string.title': '‪Onda en una cuerda‬',
  },
  es: {
    'JOIST/HomeButton.name': '‪Home‬',
    'JOIST/adaptedFrom': '‪Adaptación de‬',
    'JOIST/termsPrivacyAndLicensing': '‪Términos, privacidad y licencias‬',
    'JOIST/translation.credits.link': '‪Créditos de traducción‬',
    'JOIST/thirdParty.credits.link': '‪Créditos de terceros‬',
    'JOIST/credits.title': '‪Créditos‬',
    'JOIST/credits.leadDesign': '‪Elaboración de diseño:  {0}‬',
    'JOIST/credits.softwareDevelopment': '‪Desarrollo de software {0}‬',
    'JOIST/credits.team': '‪Equipo: {0}‬',
    'JOIST/credits.qualityAssurance': '‪Seguro de calidad: {0}‬',
    'JOIST/credits.graphicArts': '‪Artes gráficas:  {0}‬',
    'JOIST/credits.translation': '‪Traducción‬',
    'JOIST/credits.thanks': '‪Gracias‬',
    'JOIST/updates.upToDate': '‪La simulación está realizada al día ...‬',
    'JOIST/updates.outOfDate': '‪Nueva versión disponible‬',
    'JOIST/updates.checking': '‪Buscando actualizaciones...‬',
    'JOIST/updates.offline': '‪No se pueden buscar actualizaciones‬',
    'JOIST/updates.newVersionAvailable':
      '‪Hay una nueva versión disponible {0}‬',
    'JOIST/updates.yourCurrentVersion': '‪Su versión actual es: {0}.‬',
    'JOIST/updates.getUpdate': '‪Actualizar...‬',
    'JOIST/updates.noThanks': '‪No, gracias‬',
    'JOIST/versionPattern': '‪Versión {0}‬',
    'JOIST/options.title': '‪Opciones‬',
    'JOIST/showPointers': '‪Punteros de muestra‬',
    'JOIST/done': '‪Hecho‬',
    'JOIST/title.settings': '‪Configuraciones‬',
    'JOIST/menuItem.options': '‪Opciones‬',
    'JOIST/menuItem.about': '‪Acerca de...‬',
    'JOIST/menuItem.mailInputEventsLog':
      '‪Mail registrado para ingreso de sucesos‬',
    'JOIST/menuItem.outputInputEventsLog':
      '‪Registro de ingreso y salida de sucesos‬',
    'JOIST/menuItem.phetWebsite': '‪Sitio web PhET‬',
    'JOIST/menuItem.reportAProblem': '‪Informe un problema‬',
    'JOIST/menuItem.screenshot': '‪Captura de pantalla‬',
    'JOIST/menuItem.fullscreen': '‪Pantalla completa‬',
    'JOIST/menuItem.settings': '‪Configuraciones‬',
    'JOIST/menuItem.getUpdate': '‪Buscar actualizaciones...‬',
    'JOIST/menuItem.submitInputEventsLog':
      '‪Enviar registro de entrada de sucesos‬',
    'JOIST/PhetButton.name': '‪PhET Menu Button‬',
    'JOIST/titlePattern': '‪{0} {1}‬',
    'SCENERY_PHET/ResetAllButton.name': '‪Reset All‬',
    'WAVE_ON_A_STRING/rulers': '‪Reglas‬',
    'WAVE_ON_A_STRING/timer': '‪Cronómetro‬',
    'WAVE_ON_A_STRING/referenceLine': '‪Líneas de referencia‬',
    'WAVE_ON_A_STRING/tension': '‪tensión‬',
    'WAVE_ON_A_STRING/damping': '‪amortiguación‬',
    'WAVE_ON_A_STRING/low': '‪baja‬',
    'WAVE_ON_A_STRING/high': '‪alta‬',
    'WAVE_ON_A_STRING/none': '‪ninguna‬',
    'WAVE_ON_A_STRING/lots': '‪mucha‬',
    'WAVE_ON_A_STRING/frequency': '‪frecuencia‬',
    'WAVE_ON_A_STRING/patternValueUnitHz': '‪{0} Hz‬',
    'WAVE_ON_A_STRING/pulseWidth': '‪ancho del pulso‬',
    'WAVE_ON_A_STRING/patternValueUnitS': '‪{0} s‬',
    'WAVE_ON_A_STRING/amplitude': '‪amplitud‬',
    'WAVE_ON_A_STRING/patternValueUnitCm': '‪{0} cm‬',
    'WAVE_ON_A_STRING/restart': '‪Reiniciar‬',
    'WAVE_ON_A_STRING/speedSlow': '‪Movimiento lento‬',
    'WAVE_ON_A_STRING/speedNormal': '‪Normal‬',
    'WAVE_ON_A_STRING/manual': '‪Manual‬',
    'WAVE_ON_A_STRING/oscillate': '‪Oscilar‬',
    'WAVE_ON_A_STRING/pulse': '‪Pulso‬',
    'WAVE_ON_A_STRING/fixedEnd': '‪Extremo fijo‬',
    'WAVE_ON_A_STRING/looseEnd': '‪Extremo libre‬',
    'WAVE_ON_A_STRING/noEnd': '‪Sin extremo‬',
    'WAVE_ON_A_STRING/unitCm': '‪cm‬',
    'WAVE_ON_A_STRING/wave-on-a-string.title': '‪Onda en una cuerda‬',
  },
  en: {
    'JOIST/HomeButton.name': '‪Home‬',
    'JOIST/adaptedFrom': '‪adapted\nfrom‬',
    'JOIST/termsPrivacyAndLicensing': '‪Terms, Privacy & Licensing‬',
    'JOIST/translation.credits.link': '‪Translation Credits‬',
    'JOIST/thirdParty.credits.link': '‪Third-party Credits‬',
    'JOIST/credits.title': '‪Credits‬',
    'JOIST/credits.leadDesign': '‪Lead Design: {0}‬',
    'JOIST/credits.softwareDevelopment': '‪Software Development: {0}‬',
    'JOIST/credits.team': '‪Team: {0}‬',
    'JOIST/credits.qualityAssurance': '‪Quality Assurance: {0}‬',
    'JOIST/credits.graphicArts': '‪Graphic Arts: {0}‬',
    'JOIST/credits.translation': '‪Translation‬',
    'JOIST/credits.thanks': '‪Thanks‬',
    'JOIST/updates.upToDate': '‪This simulation is up to date.‬',
    'JOIST/updates.outOfDate': '‪New version available‬',
    'JOIST/updates.checking': '‪Checking for updates…‬',
    'JOIST/updates.offline': '‪Unable to check for updates.‬',
    'JOIST/updates.newVersionAvailable':
      '‪There is a new version available: {0}.‬',
    'JOIST/updates.yourCurrentVersion': '‪Your current version is: {0}.‬',
    'JOIST/updates.getUpdate': '‪Get Update…‬',
    'JOIST/updates.noThanks': '‪No Thanks‬',
    'JOIST/versionPattern': '‪version {0}‬',
    'JOIST/options.title': '‪Options‬',
    'JOIST/showPointers': '‪Show Pointers‬',
    'JOIST/done': '‪Done‬',
    'JOIST/title.settings': '‪Settings‬',
    'JOIST/menuItem.options': '‪Options…‬',
    'JOIST/menuItem.about': '‪About…‬',
    'JOIST/menuItem.mailInputEventsLog': '‪Mail Input Events Log‬',
    'JOIST/menuItem.outputInputEventsLog': '‪Output Input Events Log‬',
    'JOIST/menuItem.phetWebsite': '‪PhET Website…‬',
    'JOIST/menuItem.reportAProblem': '‪Report a Problem…‬',
    'JOIST/menuItem.screenshot': '‪Screenshot‬',
    'JOIST/menuItem.fullscreen': '‪Full Screen‬',
    'JOIST/menuItem.settings': '‪Settings…‬',
    'JOIST/menuItem.getUpdate': '‪Check for Updates…‬',
    'JOIST/menuItem.submitInputEventsLog': '‪Submit Input Events Log‬',
    'JOIST/PhetButton.name': '‪PhET Menu Button‬',
    'JOIST/titlePattern': '‪{0} {1}‬',
    'SCENERY_PHET/ResetAllButton.name': '‪Reset All‬',
    'WAVE_ON_A_STRING/rulers': '‪Rulers‬',
    'WAVE_ON_A_STRING/timer': '‪Timer‬',
    'WAVE_ON_A_STRING/referenceLine': '‪Reference Line‬',
    'WAVE_ON_A_STRING/tension': '‪Tension‬',
    'WAVE_ON_A_STRING/damping': '‪Damping‬',
    'WAVE_ON_A_STRING/low': '‪Low‬',
    'WAVE_ON_A_STRING/high': '‪High‬',
    'WAVE_ON_A_STRING/none': '‪None‬',
    'WAVE_ON_A_STRING/lots': '‪Lots‬',
    'WAVE_ON_A_STRING/frequency': '‪Frequency‬',
    'WAVE_ON_A_STRING/patternValueUnitHz': '‪{0} Hz‬',
    'WAVE_ON_A_STRING/pulseWidth': '‪Pulse Width‬',
    'WAVE_ON_A_STRING/patternValueUnitS': '‪{0} s‬',
    'WAVE_ON_A_STRING/amplitude': '‪Amplitude‬',
    'WAVE_ON_A_STRING/patternValueUnitCm': '‪{0} cm‬',
    'WAVE_ON_A_STRING/restart': '‪Restart‬',
    'WAVE_ON_A_STRING/speedSlow': '‪Slow Motion‬',
    'WAVE_ON_A_STRING/speedNormal': '‪Normal‬',
    'WAVE_ON_A_STRING/manual': '‪Manual‬',
    'WAVE_ON_A_STRING/oscillate': '‪Oscillate‬',
    'WAVE_ON_A_STRING/pulse': '‪Pulse‬',
    'WAVE_ON_A_STRING/fixedEnd': '‪Fixed End‬',
    'WAVE_ON_A_STRING/looseEnd': '‪Loose End‬',
    'WAVE_ON_A_STRING/noEnd': '‪No End‬',
    'WAVE_ON_A_STRING/unitCm': '‪cm‬',
    'WAVE_ON_A_STRING/wave-on-a-string.title': '‪Wave on a String‬',
  },
}
